### ISSUE TITLE
--parse-tree option simply prints the source code - by design?

### ISSUE THREAD

**Issue by mbdevpl** [CodethinkLabs/ofc#34]
I was really happy to find this in readme as one of the goals: "Produce an alternative FORTRAN front-end for open-source compilers.".

After cloning and running `make`, I do the following:

```
$ cat tests/programs/array.f
      PROGRAM array
        INTEGER a(16)
        INTEGER b(5)
        b = a(1:5) * 5
      END PROGRAM array
$ ./ofc --parse-tree tests/programs/array.f
      PROGRAM array
        INTEGER a(16)
        INTEGER b(5)
        b = a(1:5) * 5
      END PROGRAM array

Warning:tests/programs/array.f:2,16:
   Variable 'a' read but never written
        INTEGER a(16)
                ^
Warning:tests/programs/array.f:3,16:
   Variable 'b' written but never read
        INTEGER b(5)
                ^
$ 
```

Is the output of `ofc --parse-tree` intended just for humans? Or, can the parse tree be output also in some more program-friendly format? In other words, is there a way to print the parse tree in any other way than as source code?

I find it hard to believe that actually one options of the parser is to... print the source code.

Just in case I was misunderstood: I don't mean to complain, I'm just looking for a way to use `ofc` as a parser for a source-to-source compiler I'm working on. Can I use `ofc` for that in its current form?

**Comment by ctgriffiths** [comment]
--parse-tree prints our internal parse tree as Fortran. It is not reprinting the input source directly, if you look at some of the other tests in the repository the change is more obvious. We used this to verify our parser was correct when we first started on OFC by passing the output to GFortran. For some of the NIST tests GFortran could compile our parse output where it could not compile the source directly.

For other formats, it’s a case of adding additional print functions for each of the parse tree objects. I suspect you would want to take our –sema-tree output though as that is post transformation, rather than dealing with the legacy Fortran features.

I will not have time to work on OFC in the next few weeks but which parse tree format do you require? It could make for an interesting addition.
