### ISSUE TITLE
'dprintf', used in 'ofc_colstr_dfprintf', is not ubiquitously available on Unix

### ISSUE THREAD

**Issue by greengoblinbear** [CodethinkLabs/ofc#35]
Despite man page suggestions to the contrary, 'dprintf' is not generally available as a global definition on Unix (and specifically not on Solaris/Sparc).  The OFC function 'ofc_colstr_fdprintf' (defined in 'colster.c' and called from 'main.c') uses 'dprintf' in its implementation, and so OFC did not at first link on Solaris/Sparc.

The good news is that, after implementing 'dprintf' (using 'vsprintf' (to write to a fixed-size buffer, which is not ideal, but "good enough") and 'write' to write the buffer to the (opaque integer) file handle, OFC links and runs on Solaris.

Note also that, although 'ofc_colstr_fdprintf' takes a file handle, its only call passes in 'STDOUT_FILENO', in which case the call is equivalent to 'printf'.  If there is a deeper purpose to the implementation taking a file handle (which at present is never used except to be 'stdout') the reason is not obvious and should be documented.  (More generally, the code should be documented, but that's a separate Issue).

**Comment by ben-brewer-codethink** [comment]
Hey, this sounds like a useful fix that we should probably have in mainline.

The fixed size buffer doesn't sound ideal, you can see on line 365 of colstr.c that there's a way to get the required buffer size for printf output.

You're probably right about it only writing to standard output for now, but we kept it this way because in the future we may want to print different stages out to files rather than having a large unseparated glob of output.

It's hard to document a large and fast moving codebase without documentation becoming outdated, but if you find places where you feel additional comments would be helpful then we'd be more than happy to accept patches for that.

If you can update your patch not to used fixed buffers and submit, then we'll gladly accept it.

**Comment by ben-brewer-codethink** [comment]
This should be fixed in:
https://github.com/CodethinkLabs/ofc/commit/c020741bcbec74021909862122148fe0ede9445f

If you have time to confirm this fix I'd be grateful.
Thanks for the info and patch.
